language: python
python:
  - "3.8.5"
dist: focal
services:
  - docker
before_script:
  - docker-compose up -d --build
  - docker-compose exec web python manage.py collectstatic --noinput
script:
  - docker-compose exec web pytest -n 2
