language: python
python:
  - "3.8.5"
dist: focal
services:
  - docker
before_script:
  - docker --version
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.26.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d --build
  - docker --version
  - docker-compose --version
  - docker ps -a
  - docker-compose exec web python manage.py collectstatic --noinput
script:
  - docker-compose exec web pytest -n 2
