version: "3.8"

services:
  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    environment:
      # - "DJANGO_SECRET_KEY=<replace_it_with_your_secret_key>"
      - "DEBUG=False"
      # - "ENVIRONMENT=production"
      # - "DATABASE_URL=<replace_it_with_your_dburl>"
      # - "MEMCACHIER_SERVERS=<replace_it_with_your_server_ips>"
      # - "MEMCACHIER_USERNAME=<replace_it_with_your_username>"
      # - "MEMCACHIER_PASSWORD=<replace_it_with_your_password>"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
