version: "3.8"

services:
  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    environment:
      - "DJANGO_SECRET_KEY=Sy2COSlhcSUSzw9bDpBCRDs7Pxew9BeVZ8JwrfkqhnWPyIZecx4"
      - "DEBUG=False"
      - "ENVIRONMENT=development"
      # - "DATABASE_URL=<replace_it_with_your_db_url>"
      # - "REDIS_URL=<replace_it_with_your_redis_url>"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
